### PR TITLE
remove unnecessary try/catch

### PR DESCRIPTION
**Pull request by jessetane**
First, thank you for this great library.

I got bitten by the fact that it calls user code inside try blocks. This created an extremely difficult to debug situation caused not by a bug in this library, but by a bug in one of my callbacks!

It's not the first time this has happened to me and I've learned generally that try/catch should only be used to wrap sync code that executes outside the js main thread (in this case, dgram.send) - if there are bugs in thread where we can fix them, I say we should not hesitate to readily crash programs so that they might all be revealed.

That said, I've been running your code as patched here without issue for a few days. I know the diff looks super confusing, however all it does it remove try catch except around dgram.send calls as mentioned above.

### CODE REVIEW

**Comment by jessetane** [comment]
> ...should only be used to wrap sync code that executes outside the js main thread

I just mean, outside of "javascript land" here

**Comment by stephenwvickers** [comment]
Hi @jessetane 

Thank you for this patch.  Before I start to work through it, can you please explain in more detail what is wrong with the existing code?

The try/catch blocks are there so that you don't have to deal with exception handling _and_ callback with error semantics at the same time.  If an exception is thrown it's considered bad, and you shouldn't try to catch it.  Any other recoverable error should be passed to the callback, or result in an error event being emitted from the session.

Can you provide an example of why it needs to be changed?

Many thanks

Steve

**Comment by jessetane** [comment]
Consider what will happen if the user's callback (or some other method it calls) crashes synchronously here:
https://github.com/stephenwvickers/node-net-snmp/blob/master/index.js#L919

The user's callback will be invoked a second time, this time with the error from its own crash. Depending on the callback's logic, things can get weird here. Contrived example:

``` javascript
function doThing (cb) {
  try {
    var err = new Error('bad')
    err.code = 1
    cb(err)
  } catch (err) {
    cb(err)
  }
}

doThing(err => {
  if (err.code === 1) {
    throw new Error('oops crash')
    console.error(err)
  } else {
    console.log('everything is ok')
  }
})

// => everything is ok
```

As far as I can tell, none of the library's code in `onMsg` can fail unless the user messed up. If the user messed up, the library should just let the crash happen (or handle the error explicitly somehow).

**Comment by jessetane** [comment]
Googling "try catch javascript" turned up this, same issue in someone else's words: https://willhaley.com/blog/try-catch-callbacks-in-javascript/

**Comment by jessetane** [comment]
See also Raynos' answer here: https://softwareengineering.stackexchange.com/questions/144326/try-catch-in-javascript-isnt-it-a-good-practice

**Comment by jessetane** [comment]
I see after looking a bit closer that the `ResponseMessage` constructor could legitimately throw... and that `send` probably can't. Pushing fixes for those cases in just a sec.

**Comment by stephenwvickers** [comment]
Hi @jessetane 

Thanks for the extra information, you make a good point regarding the user callback being called twice when it itself crashes.

I will try to take a look at this over the weekend, failing that early next week.

Thanks

Steve

**Comment by jessetane** [comment]
Thanks. I wasted an hour on this as I was using it with another 3rd party library that apparently wraps callbacks to prevent them from accidentally being invoked twice, so the error from the crash was silenced completely. I guess the try / catch rule of thumb is that we should just never use it around calls to the user's code (e.g. around callback invocations).

**Comment by markabrahams** [comment]
Hi @jessetane - just had a look at this PR now, and it seems this behaviour is still desirable, even though the code base has changed a bit in the last two years.

If you're able to merge the current master into your PR and update to resolve merge conflicts, and then I'll look to merge this change.

**Comment by markabrahams** [comment]
Hi @jessetane - I've just manually merged this change into the new codebase and published in v2.7.7 of the npm.

**Pull request closed without merging**
