### PR TITLE
Implements the provider side of sub-types (revamp)

### PR DESCRIPTION
**Pull request by derrell**
This PR replaces #158 which was based on a branch that was ultimately discarded. The relevant changes pertaining to sub-types -- range and size constraints -- have been pulled into this branch based on today's master.

### CODE REVIEW

**Comment by derrell** [comment]
This PR, like its predecessor, implements only the provider side of sub-types. The parser changes are still needed.

**Comment by markabrahams** [comment]
Thanks heaps for the rebase here @derrell!  Looks like a nice easy-to-use structure there in the provider.  I've merged this into master now, and published in version 3.3.0 of the npm.

Were you looking to do the parser changes at some point?  Or I can have a crack at when I get a moment?

Also, it might be a good idea to update the README with this new constraints stuff if you don't mind doing that?  (I still owe the README some agent callback varbind fields as well myself!)

**Comment by derrell** [comment]
I'll be glad to update the README, but I'll leave the parser changes for you, ok?

**Comment by markabrahams** [comment]
Thanks!  Yep - no problems - I'll look into the parser.

**Pull request merged**
