### PR TITLE
Generate events to the app, for agent operations

### PR DESCRIPTION
**Pull request by derrell**
There are events for each significant operation that occurs while processing an agent request. Internally, these are EventEmitter events. Ultimately, we might choose to expose the event emitter in documentation. For now, the events are listened to internally, and a registered callback function is called, with the event data. and it need be only that interface that gets documented.

This PR sits atop the row-status one. That one should be completed first. This, however, shows my WIP on agent events to the app. I'll be working with this over the next days, ensuring that it provides the proper information, and incorporating it into an app requiring mib value persistence over restarts.

### CODE REVIEW

**Comment by derrell** [comment]
The original issue and discussion about this topic is in #141.

**Comment by markabrahams** [comment]
Yep - as you say - let's focus on getting the row-status PR merged and then we can tackle this.

**Comment by derrell** [comment]
@markabrahams The demo has been updated to show how persistence could (poorly, but demonstrably) be achieved. This, I think, proves out the new feature's abilities. I don't see how this could be accomplished reasonably, via the existing provider handler, but I'd like to hear your thoughts. (See my comments in #141)

**Comment by derrell** [comment]
I've removed the WIP indicator here. This is ready for review immediately (ignoring the row-status changes) , and for merging as soon as the row-status branch is merged.

**Comment by markabrahams** [comment]
Persistence storage feature (issue #141) has now been implemented drawing inspiration from this PR but with some modifications.

**Pull request closed without merging**
