### PR TITLE
Implements the provider side of sub-types

### PR DESCRIPTION
**Pull request by derrell**
This PR sits atop of the Row Status and Agent Events PRs. If you want to look at the specific changes for this PR before merging those, they are isolated to the `setValue` method in index.js, and constraints added for testing, in snmp-agent.js

### CODE REVIEW

**Comment by derrell** [comment]
See #156

**Comment by markabrahams** [comment]
Hey @derrell - are you able to rebase this PR to base off the latest master?

**Comment by derrell** [comment]
I'm just on my phone right now. When I get back to my computer later
tonight or tomorrow, I'll do so.

**Comment by derrell** [comment]
Obsoleted by #161

**Pull request closed without merging**
